version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: "Download dependencies"
          command: mvn dependency:resolve
      - run:
          name: "Compile and test"
          command: mvn clean verify

  package:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: "Package the JAR"
          command: mvn package

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
      - package:
          requires:
            - build