version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Test
          command: mvn test

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  sample:
    jobs:
      - build-and-test
      - codecov/upload:
          requires:
            - build-and-test
